name: Bolt Python
jobs:
  Job1:
    name: Job 1
    steps:
      - type: gradle
        working-directory: .git
        use-gradle-wrapper: ''
    runs-on: Linux-Medium
    enable-dependency-cache: true
    parallelism: 3
